version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your-password
      MYSQL_DATABASE: taskmanager
    ports:
      - "3306:3306"
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
